# Generated by Django 2.0.13 on 2020-04-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_delete',
            field=models.CharField(default='N', max_length=2, verbose_name='逻辑删除'),
        ),
    ]
